#Build Image
FROM node:18 AS build

WORKDIR /app

COPY . ./
RUN npm install
RUN npm run build

#-------------------

#Deploy Image
FROM node:18-alpine AS deploy-node

WORKDIR /app

COPY --from=build /app/build .

ENTRYPOINT [ "node", "index.js" ]
